---
- name: Installer Myql
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - python-mysqldb
    - mysql-server
    - mysql-client

- name: S'assurer que MySQL est en fonctionnement
  action: service name=mysql state=started

- name: Copier le .my.cnf avec les informations de connection.
  template: src=templates/my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Mettre à jour le mot de passe root MySQL pour tous les comptes root
  action: mysql_user name=root password={{ mysql_root_db_password  }} host_all=yes

- name: S'assurez-vous que les utilisateurs anonymes ne sont pas dans la base de données
  action: mysql_user name='' host={{ item }} state=absent
  with_items:
    - $ansible_hostname
    - localhost

- name: Créer une base de données MySQL
  action: mysql_db name={{ item.name  }} state=present encoding=utf8mb4
  with_items: '{{ sites_to_set_up }}'

- name: Créer un utilisateur MySQL
  action: mysql_user name={{ item.name  }} priv={{ item.name  }}.*:ALL state=present password="{{ item.mysql_password }}"
  with_items: '{{ sites_to_set_up }}'
